export const URL = "https://aster.deno.dev/"
export const POSTS_URL = import.meta.env.DEV ? "/posts.json" : URL + "posts.json"
export const KOFI_URL = "https://ko-fi.com/4ster/"
export const GITHUB_URL = "https://github.com/4ster-light/"
export const X_URL = "https://x.com/4ster_light/"
export const BANNER_URL = import.meta.env.DEV ? "/banner.jpg" : URL + "banner.png"
export const PFP_URL = import.meta.env.DEV ? "/pfp.jpg" : URL + "pfp.jpg"
export const UNI_URL = "https://uclm.es/"
