name: Deploy

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Pnpm
        uses: pnpm/action-setup@v2
        with:
          version: v10.x

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: deno task build
        env:
          GH_API: ${{ vars.GH_API }}

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "aster"
          entrypoint: "index.js"
          root: "build"
